name: add article
description: contribute an article about crazy thursday
title: thanks for taking the time to contribute article about crazy-thursday.
labels: ["add article"]
body:
  - type: textarea
    id: article
    attributes:
      description: you can leave the crazy thursday article here. markdown format is suggested, and the command ``crazy-thursday`` can render markdown in terminal.
      placeholder: v me 50!
    validations:
      required: true
